ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Copy the prom.yml configuration file to the container
COPY grafana/datasources /etc/grafana/provisioning/datasources
COPY grafana/dashboards /etc/grafana/provisioning/dashboards

# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
