ARG VERSION=v3.2.1
FROM prom/prometheus:${VERSION}

# Копіюємо тільки конфігурацію Prometheus 
COPY prometheus/prom.yml /etc/prometheus/prom.yml

# Команда для запуску Prometheus 
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
