ARG VERSION=11.5.2
FROM grafana/grafana-oss:${VERSION}

# Вказуємо повний шлях до папок у репозиторії
COPY grafana/datasources /etc/grafana/provisioning/datasources
COPY grafana/dashboards /etc/grafana/provisioning/dashboards
