ARG VERSION=11.5.2
FROM grafana/grafana-oss:${VERSION}

# Вказуємо повний шлях до папок у репозиторії
COPY grafana/datasources /etc/grafana/provisioning/datasources
COPY grafana/dashboards /etc/grafana/provisioning/dashboards

ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
