ARG VERSION=11.5.2
FROM grafana/grafana-oss:${VERSION}

# Копіюємо тільки те, що точно є, і додаємо анонімний вхід
COPY grafana/datasources* /etc/grafana/provisioning/datasources/

ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
